# vouch config
# bare minimum to get vouch running with OpenID Connect (such as okta)

vouch:
    listen: 0.0.0.0
    port: 9090
    allowAllUsers: true
  
    jwt:
      secret: Your-64-character-secret-key-here
      issuer: Vouch
      compress: false
  
    cookie:
      name: my-vouch-ct
      secure: false
      domain: localhost
  
    headers:
      jwt: X-Vouch-Token
      querystring: access_token
      redirect: X-Vouch-Requested-URI
      accesstoken: X-Vouch-IdP-AccessToken
      idtoken: X-Vouch-IdP-IdToken
  
    post_logout_redirect_uris:
      - https://your-project-name-here.eu.auth0.com/v2/logout?client_id={client_id_from_auth0}&returnTo=https://localhost/
  
oauth:
    # Generic OpenID Connect
    # including okta
    provider: oidc
    client_id: {client_id_from_auth0}
    client_secret: {client_secret_from_auth0}
    auth_url: https://your-project-name-here.eu.auth0.com/authorize
    token_url: https://your-project-name-here.eu.auth0.com/oauth/token
    user_info_url: https://your-project-name-here.eu.auth0.com/userinfo
    scopes:
        - openid
        - email
        - profile
    callback_url: https://localhost/sso/auth
